
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.board
{
public sealed partial class BoardLayout : Luban.BeanBase
{
    public BoardLayout(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Columns = _buf.ReadInt();
        Rows = _buf.ReadInt();
        CellSize = _buf.ReadFloat();
        ReservedBorderWidth = _buf.ReadInt();
        {int __n0 = _buf.ReadSize(); OpenCells = new int[__n0][];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int[] __e0;{int __n1 = _buf.ReadSize(); __e0 = new int[__n1];for(var __index1 = 0 ; __index1 < __n1 ; __index1++) { int __e1;__e1 = _buf.ReadInt(); __e0[__index1] = __e1;}} OpenCells[__index0] = __e0;}}
        NormalGlassId = _buf.ReadInt();
        NormalGlassId_Ref = null;
        ColoredGlassId = _buf.ReadInt();
        ColoredGlassId_Ref = null;
        {int __n0 = _buf.ReadSize(); ColoredGlassCell = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ColoredGlassCell[__index0] = __e0;}}
    }

    public static BoardLayout DeserializeBoardLayout(ByteBuf _buf)
    {
        return new board.BoardLayout(_buf);
    }

    /// <summary>
    /// 布局ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 列数
    /// </summary>
    public readonly int Columns;
    /// <summary>
    /// 行数
    /// </summary>
    public readonly int Rows;
    /// <summary>
    /// 格子尺寸
    /// </summary>
    public readonly float CellSize;
    /// <summary>
    /// 保留边框宽度
    /// </summary>
    public readonly int ReservedBorderWidth;
    /// <summary>
    /// 开放坐标(column,row)
    /// </summary>
    public readonly int[][] OpenCells;
    /// <summary>
    /// 普通玻璃ID
    /// </summary>
    public readonly int NormalGlassId;
    public glass.Glass NormalGlassId_Ref;
    /// <summary>
    /// 彩色玻璃ID
    /// </summary>
    public readonly int ColoredGlassId;
    public glass.Glass ColoredGlassId_Ref;
    /// <summary>
    /// 彩色玻璃坐标(column,row)
    /// </summary>
    public readonly int[] ColoredGlassCell;
   
    public const int __ID__ = -847726968;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        NormalGlassId_Ref = tables.TbGlass.GetOrDefault(NormalGlassId);
        ColoredGlassId_Ref = tables.TbGlass.GetOrDefault(ColoredGlassId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "columns:" + Columns + ","
        + "rows:" + Rows + ","
        + "cellSize:" + CellSize + ","
        + "reservedBorderWidth:" + ReservedBorderWidth + ","
        + "openCells:" + Luban.StringUtil.CollectionToString(OpenCells) + ","
        + "normalGlassId:" + NormalGlassId + ","
        + "coloredGlassId:" + ColoredGlassId + ","
        + "coloredGlassCell:" + Luban.StringUtil.CollectionToString(ColoredGlassCell) + ","
        + "}";
    }
}
}

