
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.board
{
/// <summary>
/// 棋盘布局配置
/// </summary>
public partial class TbBoardLayout
{
    private readonly System.Collections.Generic.Dictionary<int, board.BoardLayout> _dataMap;
    private readonly System.Collections.Generic.List<board.BoardLayout> _dataList;
    
    public TbBoardLayout(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, board.BoardLayout>(n);
        _dataList = new System.Collections.Generic.List<board.BoardLayout>(n);
        for(int i = n ; i > 0 ; --i)
        {
            board.BoardLayout _v;
            _v = global::GameConfig.board.BoardLayout.DeserializeBoardLayout(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, board.BoardLayout> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<board.BoardLayout> DataList => _dataList;

    public board.BoardLayout GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public board.BoardLayout Get(int key) => _dataMap[key];
    public board.BoardLayout this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

