
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private item.TbItem m_TbItem;
    public item.TbItem TbItem 
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new item.TbItem(defaultLoader("item_tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }
    private globalcfg.TbGlobal m_TbGlobal;
    public globalcfg.TbGlobal TbGlobal 
    {
        get
        {
            if (m_TbGlobal == null)
            {
                m_TbGlobal = new globalcfg.TbGlobal(defaultLoader("globalcfg_tbglobal"));
                m_TbGlobal.ResolveRef(this);
            }
            return m_TbGlobal;
        }
        set
        {
            m_TbGlobal = value;
            m_TbGlobal.ResolveRef(this);
        }
    }
    /// <summary>
    /// 机器人
    /// </summary>
    private robot.TbRobot m_TbRobot;
    public robot.TbRobot TbRobot 
    {
        get
        {
            if (m_TbRobot == null)
            {
                m_TbRobot = new robot.TbRobot(defaultLoader("robot_tbrobot"));
                m_TbRobot.ResolveRef(this);
            }
            return m_TbRobot;
        }
        set
        {
            m_TbRobot = value;
            m_TbRobot.ResolveRef(this);
        }
    }
    /// <summary>
    /// 机器人占格形状
    /// </summary>
    private robot.TbRobotShape m_TbRobotShape;
    public robot.TbRobotShape TbRobotShape 
    {
        get
        {
            if (m_TbRobotShape == null)
            {
                m_TbRobotShape = new robot.TbRobotShape(defaultLoader("robot_tbrobotshape"));
                m_TbRobotShape.ResolveRef(this);
            }
            return m_TbRobotShape;
        }
        set
        {
            m_TbRobotShape = value;
            m_TbRobotShape.ResolveRef(this);
        }
    }
    /// <summary>
    /// 掉落配置
    /// </summary>
    private drop.TbDrop m_TbDrop;
    public drop.TbDrop TbDrop 
    {
        get
        {
            if (m_TbDrop == null)
            {
                m_TbDrop = new drop.TbDrop(defaultLoader("drop_tbdrop"));
                m_TbDrop.ResolveRef(this);
            }
            return m_TbDrop;
        }
        set
        {
            m_TbDrop = value;
            m_TbDrop.ResolveRef(this);
        }
    }
    /// <summary>
    /// 玻璃配置
    /// </summary>
    private glass.TbGlass m_TbGlass;
    public glass.TbGlass TbGlass 
    {
        get
        {
            if (m_TbGlass == null)
            {
                m_TbGlass = new glass.TbGlass(defaultLoader("glass_tbglass"));
                m_TbGlass.ResolveRef(this);
            }
            return m_TbGlass;
        }
        set
        {
            m_TbGlass = value;
            m_TbGlass.ResolveRef(this);
        }
    }
    /// <summary>
    /// 棋盘布局配置
    /// </summary>
    private board.TbBoardLayout m_TbBoardLayout;
    public board.TbBoardLayout TbBoardLayout 
    {
        get
        {
            if (m_TbBoardLayout == null)
            {
                m_TbBoardLayout = new board.TbBoardLayout(defaultLoader("board_tbboardlayout"));
                m_TbBoardLayout.ResolveRef(this);
            }
            return m_TbBoardLayout;
        }
        set
        {
            m_TbBoardLayout = value;
            m_TbBoardLayout.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
