
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.drop
{
public sealed partial class Drop : Luban.BeanBase
{
    public Drop(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        {int __n0 = _buf.ReadSize(); Package = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Package[__index0] = __e0;}}
    }

    public static Drop DeserializeDrop(ByteBuf _buf)
    {
        return new drop.Drop(_buf);
    }

    /// <summary>
    /// 掉落配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 掉落类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 掉落包：ID与权重交替排列
    /// </summary>
    public readonly int[] Package;
   
    public const int __ID__ = -560158034;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "package:" + Luban.StringUtil.CollectionToString(Package) + ","
        + "}";
    }
}
}

