
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.drop
{
/// <summary>
/// 掉落配置
/// </summary>
public partial class TbDrop
{
    private readonly System.Collections.Generic.Dictionary<int, drop.Drop> _dataMap;
    private readonly System.Collections.Generic.List<drop.Drop> _dataList;
    
    public TbDrop(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, drop.Drop>(n);
        _dataList = new System.Collections.Generic.List<drop.Drop>(n);
        for(int i = n ; i > 0 ; --i)
        {
            drop.Drop _v;
            _v = global::GameConfig.drop.Drop.DeserializeDrop(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, drop.Drop> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<drop.Drop> DataList => _dataList;

    public drop.Drop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public drop.Drop Get(int key) => _dataMap[key];
    public drop.Drop this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

