
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.glass
{
public sealed partial class Glass : Luban.BeanBase
{
    public Glass(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Kind = _buf.ReadInt();
        MaxDurability = _buf.ReadInt();
        HitDurabilityLoss = _buf.ReadInt();
        PrefabLocation = _buf.ReadString();
        {int __n0 = _buf.ReadSize(); StageUpperRatios = new float[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { float __e0;__e0 = _buf.ReadFloat(); StageUpperRatios[__index0] = __e0;}}
        {int __n0 = _buf.ReadSize(); StageSprites = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); StageSprites[__index0] = __e0;}}
    }

    public static Glass DeserializeGlass(ByteBuf _buf)
    {
        return new glass.Glass(_buf);
    }

    /// <summary>
    /// 玻璃ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 种类：0 Normal，1 Colored
    /// </summary>
    public readonly int Kind;
    /// <summary>
    /// 最大耐久
    /// </summary>
    public readonly int MaxDurability;
    /// <summary>
    /// 每次命中耐久损失
    /// </summary>
    public readonly int HitDurabilityLoss;
    /// <summary>
    /// Prefab资源地址
    /// </summary>
    public readonly string PrefabLocation;
    /// <summary>
    /// 阶段耐久比上限
    /// </summary>
    public readonly float[] StageUpperRatios;
    /// <summary>
    /// 阶段图片资源地址
    /// </summary>
    public readonly string[] StageSprites;
   
    public const int __ID__ = -451182998;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "kind:" + Kind + ","
        + "maxDurability:" + MaxDurability + ","
        + "hitDurabilityLoss:" + HitDurabilityLoss + ","
        + "prefabLocation:" + PrefabLocation + ","
        + "stageUpperRatios:" + Luban.StringUtil.CollectionToString(StageUpperRatios) + ","
        + "stageSprites:" + Luban.StringUtil.CollectionToString(StageSprites) + ","
        + "}";
    }
}
}

