
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.glass
{
/// <summary>
/// 玻璃配置
/// </summary>
public partial class TbGlass
{
    private readonly System.Collections.Generic.Dictionary<int, glass.Glass> _dataMap;
    private readonly System.Collections.Generic.List<glass.Glass> _dataList;
    
    public TbGlass(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, glass.Glass>(n);
        _dataList = new System.Collections.Generic.List<glass.Glass>(n);
        for(int i = n ; i > 0 ; --i)
        {
            glass.Glass _v;
            _v = global::GameConfig.glass.Glass.DeserializeGlass(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, glass.Glass> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<glass.Glass> DataList => _dataList;

    public glass.Glass GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public glass.Glass Get(int key) => _dataMap[key];
    public glass.Glass this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

