
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.globalcfg
{
public sealed partial class Global : Luban.BeanBase
{
    public Global(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Value = _buf.ReadFloat();
    }

    public static Global DeserializeGlobal(ByteBuf _buf)
    {
        return new globalcfg.Global(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 普通反弹随机修正范围（度）
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = -95440784;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

