
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.globalcfg
{
public partial class TbGlobal
{
    private readonly System.Collections.Generic.Dictionary<int, globalcfg.Global> _dataMap;
    private readonly System.Collections.Generic.List<globalcfg.Global> _dataList;
    
    public TbGlobal(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, globalcfg.Global>(n);
        _dataList = new System.Collections.Generic.List<globalcfg.Global>(n);
        for(int i = n ; i > 0 ; --i)
        {
            globalcfg.Global _v;
            _v = global::GameConfig.globalcfg.Global.DeserializeGlobal(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, globalcfg.Global> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<globalcfg.Global> DataList => _dataList;

    public globalcfg.Global GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public globalcfg.Global Get(int key) => _dataMap[key];
    public globalcfg.Global this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

