
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.robot
{
public sealed partial class Robot : Luban.BeanBase
{
    public Robot(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        RobotName = _buf.ReadString();
        QualityId = _buf.ReadInt();
        RobotPrefab = _buf.ReadString();
        RobotIcon = _buf.ReadString();
        ShapeId = _buf.ReadInt();
        ShapeId_Ref = null;
        SkillId = _buf.ReadInt();
    }

    public static Robot DeserializeRobot(ByteBuf _buf)
    {
        return new robot.Robot(_buf);
    }

    /// <summary>
    /// 机器人唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 机器人名称
    /// </summary>
    public readonly string RobotName;
    /// <summary>
    /// 固定品质ID
    /// </summary>
    public readonly int QualityId;
    /// <summary>
    /// 预制体资源名
    /// </summary>
    public readonly string RobotPrefab;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string RobotIcon;
    /// <summary>
    /// 占格形状ID
    /// </summary>
    public readonly int ShapeId;
    public robot.RobotShape ShapeId_Ref;
    /// <summary>
    /// 技能ID，0为未配置
    /// </summary>
    public readonly int SkillId;
   
    public const int __ID__ = 1376639430;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ShapeId_Ref = tables.TbRobotShape.GetOrDefault(ShapeId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "robotName:" + RobotName + ","
        + "qualityId:" + QualityId + ","
        + "robotPrefab:" + RobotPrefab + ","
        + "robotIcon:" + RobotIcon + ","
        + "shapeId:" + ShapeId + ","
        + "skillId:" + SkillId + ","
        + "}";
    }
}
}

