
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.robot
{
public sealed partial class RobotShape : Luban.BeanBase
{
    public RobotShape(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int __n0 = _buf.ReadSize(); CellOffsets = new int[__n0][];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int[] __e0;{int __n1 = _buf.ReadSize(); __e0 = new int[__n1];for(var __index1 = 0 ; __index1 < __n1 ; __index1++) { int __e1;__e1 = _buf.ReadInt(); __e0[__index1] = __e1;}} CellOffsets[__index0] = __e0;}}
    }

    public static RobotShape DeserializeRobotShape(ByteBuf _buf)
    {
        return new robot.RobotShape(_buf);
    }

    /// <summary>
    /// 形状唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 相对基准格的占格坐标(x,y)
    /// </summary>
    public readonly int[][] CellOffsets;
   
    public const int __ID__ = -1873563269;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "cellOffsets:" + Luban.StringUtil.CollectionToString(CellOffsets) + ","
        + "}";
    }
}
}

