
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.robot
{
/// <summary>
/// 机器人
/// </summary>
public partial class TbRobot
{
    private readonly System.Collections.Generic.Dictionary<int, robot.Robot> _dataMap;
    private readonly System.Collections.Generic.List<robot.Robot> _dataList;
    
    public TbRobot(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, robot.Robot>(n);
        _dataList = new System.Collections.Generic.List<robot.Robot>(n);
        for(int i = n ; i > 0 ; --i)
        {
            robot.Robot _v;
            _v = global::GameConfig.robot.Robot.DeserializeRobot(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, robot.Robot> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<robot.Robot> DataList => _dataList;

    public robot.Robot GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public robot.Robot Get(int key) => _dataMap[key];
    public robot.Robot this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

