
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.robot
{
/// <summary>
/// 机器人占格形状
/// </summary>
public partial class TbRobotShape
{
    private readonly System.Collections.Generic.Dictionary<int, robot.RobotShape> _dataMap;
    private readonly System.Collections.Generic.List<robot.RobotShape> _dataList;
    
    public TbRobotShape(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, robot.RobotShape>(n);
        _dataList = new System.Collections.Generic.List<robot.RobotShape>(n);
        for(int i = n ; i > 0 ; --i)
        {
            robot.RobotShape _v;
            _v = global::GameConfig.robot.RobotShape.DeserializeRobotShape(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, robot.RobotShape> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<robot.RobotShape> DataList => _dataList;

    public robot.RobotShape GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public robot.RobotShape Get(int key) => _dataMap[key];
    public robot.RobotShape this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

